[default]
timeout = 30

[DeFacto Vrn]
title = "DeFacto Воронеж"
url = "https://facto.ru"
entrySelector = "div.news-list-main div.item"
titleSelector = "div.text p.name"
linkSelector = "div.text p.name a"
